apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "url-shortener.fullname" . }}
  labels:
    app: {{ template "url-shortener.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  URLSHORTENER_POSTGRESQL_HOST: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
  URLSHORTENER_POSTGRESQL_PORT: '5432'
  URLSHORTENER_POSTGRESQL_USER: {{ .Values.postgresql.postgresUser | quote}}
  URLSHORTENER_STORAGE: postgres
  URLSHORTENER_HTTP_ADDR: ':8080'
  URLSHORTENER_FAKELOAD: 'true'
  URLSHORTENER_SD_RESOLVER: {{ template "url-shortener.fullname" . }}-resolver.{{ .Release.Namespace }}.svc.cluster.local
  URLSHORTENER_SD_SHORTENER: {{ template "url-shortener.fullname" . }}-shortener.{{ .Release.Namespace }}.svc.cluster.local
  URLSHORTENER_ZIPKIN_ADDRESS: "http://{{ template "url-shortener.fullname" . }}-zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"
