apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "url-shortener.fullname" . }}-shortener"
  labels:
    app: "{{ template "url-shortener.name" . }}-shortener"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.shortener.internalPort  | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.shortener.internalPort  | quote }}
      labels:
        app: "{{ template "url-shortener.name" . }}-shortener"
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "url-shortener.fullname" . }}
          env:
            - name: URLSHORTENER_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            - name: URLSHORTENER_ROLE
              value: "shortener"
          ports:
            - containerPort: {{ .Values.service.shortener.internalPort }}
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.shortener.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.shortener.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
